routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Web\HomeController;
use App\Http\Controllers\Web\UserController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\KhoachuyenmonController;
use App\Http\Controllers\Admin\KhoahocController;
use App\Http\Controllers\Admin\SinhvienController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::prefix('admin')->name('ad.')->group(function () {
    Route::get('login', [LoginController::class, 'index'])->name('login.index');
    Route::post('login', [LoginController::class, 'login'])->name('login');

    Route::middleware(['auth'])->group(function () {
        Route::get('/', function () {
            return view('admin.dashboard');
        })->name('dashboard');
    
        Route::resource('category', CategoryController::class)->except('show');
        Route::resource('blog', BlogController::class)->except('show');
        Route::resource('admin', AdminController::class)->except('show');

        Route::resource('sinhvien', SinhvienController::class)->except('show');
        Route::resource('khoahoc', KhoahocController::class)->except('show');
        Route::resource('khoachuyenmon', KhoachuyenmonController::class)->except('show');
    
        Route::get('logout', [LoginController::class, 'logout'])->name('logout');
        Route::get('search', [CategoryController::class, 'search'])->name('category.search');
    });

});


Route::name('w.')->namespace('Web')->group(function(){
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::get('shop', [HomeController::class, 'shop'])->name('shop');

    Route::get('login', [UserController::class, 'login'])->name('login');
    Route::post('login', [UserController::class, 'checklogin'])->name('get.login');

    Route::get('register', [UserController::class, 'register'])->name('register');
    Route::post('register', [UserController::class, 'getregister'])->name('get.register');


});





    

app/Models/Sinhvien.php
<?php

namespace App\Models;

use App\Models\Khoahoc;
use App\Models\Khoachuyenmon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Sinhvien extends Model
{
    use HasFactory;
    // protected $table = 'sinhviens';
    protected $fillable = [
    'name', 'gender', 'date', 'address', 'makhoacm_id', 'makhoahoc_id'
    ];

    public function khoachuyenmon()
    {
        return $this->belongsTo(Khoachuyenmon::class,'makhoacm_id');
    }

    public function khoahoc()
    {
        return $this->belongsTo(Khoahoc::class, 'makhoahoc_id');
    }
}

app/Http/Controllers/Admin/SinhvienController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateSinhvienRequest;
use App\Models\Khoachuyenmon;
use App\Models\Khoahoc;
use App\Models\Sinhvien;
use Illuminate\Http\Request;

class SinhvienController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $sinhviens = Sinhvien::orWhere('name', 'like', '%' . $request->search . '%')->paginate(3)->withQueryString();

        $khoahocs = Khoahoc::all();
        $khoachuyenmons = Khoachuyenmon::all();
        return view('admin.sinhvien.index', compact('sinhviens', 'khoahocs', 'khoachuyenmons'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $khoahocs = Khoahoc::all();
        $khoachuyenmons = Khoachuyenmon::all();
        return view('admin.sinhvien.create', compact('khoahocs', 'khoachuyenmons'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateSinhvienRequest $request)
    {
        $data = $request->all();
        $check = Sinhvien::create($data);
        if ($check) {
            return redirect()->route('ad.sinhvien.index')->with('success', 'thêm mới thành công');
        }
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Sinhvien $sinhvien)
    {
        return view('admin.sinhvien.edit', compact('sinhvien'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Sinhvien $sinhvien)
    {
        $data = $request->all();
        $check = $sinhvien->update($data);
        if ($check) {
            return redirect()->route('ad.sinhvien.index')->with('success', 'sửa thành công');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Sinhvien $sinhvien)
    {
        $sinhvien->delete();
        return redirect()->route('ad.sinhvien.index')->with('success', 'Xóa thành công');
    }


    
}

resources/views/admin/sinhvien/create.blade.php
@extends('admin.layouts.master')

@section('content')
    @if ($errors->any())
        <p class="alert alert-danger">
            <span>Vui lòng kiểm tra lại các trường</span>
        </p>
    @endif

    <a class="btn btn-sm btn-success" href="{{ route('ad.sinhvien.index') }}">List Danh sách</a>
    <form method="post" action="{{ route('ad.sinhvien.store') }}" class="text-white">
        @csrf
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="name">name</label>
                <input type="text" class="form-control" id="name" placeholder="name" name="name" value="{{old('name')}}">
                @error('name')
                    <span class="text-danger">{{ $message }}</span>
                @enderror
            </div>
            

            <div class="form-group col-md-6">
                <label for="address">address</label>
                <input type="text" class="form-control" id="address" placeholder="address" name="address" value="{{old('address')}}">
                @error('address')
                    <span class="text-danger">{{ $message }}</span>
                @enderror
            </div>
        </div>

        <div class="form-group">
            <label for="date">date</label>
            <input type="date" class="form-control" name="date" value="{{old('date')}}" id="date" placeholder="date">
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="gender">gender</label>
                <select name="gender" id="gender" class="form-control">
                    <option value="1" selected>Nam</option>
                    <option value="0">Nữ</option>
                </select>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="makhoahoc_id">Khóa học<span class="required">*</span></label>
                <select name="makhoahoc_id" class="form-control" id="makhoahoc_id">
                    @foreach($khoahocs as $khoahoc)
                    <option value="{{ $khoahoc->id }}">{{ $khoahoc->name }}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group col-md-6">
                <label for="makhoacm_id">Khoa chuyên môn<span class="required">*</span></label>
                <select name="makhoacm_id" class="form-control" id="makhoacm_id">
                    @foreach($khoachuyenmons as $khoachuyenmon)
                    <option value="{{ $khoachuyenmon->id }}">{{ $khoachuyenmon->name }}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <button type="submit" class="btn btn-sm btn-primary">Thêm mới</button>
    </form>
@endsection

resources/views/admin/sinhvien/edit.blade.php
@extends('admin.layouts.master')

@section('content')
    @if ($errors->any())
        <p class="alert alert-danger">
            <span>Vui lòng kiểm tra lại các trường</span>
        </p>
    @endif

    <a class="btn btn-sm btn-success" href="{{ route('ad.sinhvien.index') }}">List Danh mục</a>
    <form method="post" action="{{ route('ad.sinhvien.update', $sinhvien) }}" class="text-white">
        @csrf
        @method('PUT')
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="name">name</label>
                <input type="text" class="form-control" id="name" placeholder="name" name="name" value="{{$sinhvien->name}}">
                @error('name')
                    <span class="text-danger">{{ $message }}</span>
                @enderror
            </div>
            

            <div class="form-group col-md-6">
                <label for="address">address</label>
                <input type="text" class="form-control" id="address" placeholder="address" name="address" value="{{$sinhvien->address}}">
                @error('address')
                    <span class="text-danger">{{ $message }}</span>
                @enderror
            </div>
        </div>

        <div class="form-group">
            <label for="date">date</label>
            <input type="date" class="form-control" name="date" value="{{$sinhvien->date}}" id="date" placeholder="date">
        </div>

        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="gender">gender</label>
                <select name="gender" id="gender" class="form-control" >
                    <option value="1" selected>Nam</option>
                    <option value="0">Nữ</option>
                </select>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">Sửa</button>
    </form>
@endsection

resources/views/admin/sinhvien/index.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="row mb-3">
        <div class="col-md-6">
            <a class="btn btnsm btn btn-success"
                href="{{ route('ad.sinhvien.create') }}">Tạo mới</a>
        </div>
        <div class="col-md-6 text-right">
            <caption>
                <form class="w-100 d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control small" placeholder="Search for..."
                            aria-label="Search" aria-describedby="basic-addon2" name="search">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">
                                <i class="fa fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </caption>
        </div>
    </div>
    <table class="table table-dark table-hover text-white">
        <thead>
            <tr>
                <th scope="col">id</th>
                <th scope="col">Name</th>
                <th scope="col">Gender</th>
                <th scope="col">Ngày sinh</th>
                <th scope="col">Địa chỉ</th>
                <th scope="col">Khóa học</th>
                <th scope="col">Khoa chuyên môn</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($sinhviens as $key => $sinhvien)
                <tr>
                    {{-- <th scope="row">{{ $key + 1 }}</th> --}}
                    <th scope="row">{{ $sinhvien->id }}</th>
                    <td>{{ $sinhvien->name }}</td>
                    <td>
                        @if ($sinhvien->gender == 1)
                            <span class="btn-primary btn-sm">Nam</span>
                        @else
                            <span class="btn-warning btn-sm">Nữ</span>
                        @endif

                    </td>
                    <td>{{ $sinhvien->date }}</td>
                    <td>{{ $sinhvien->address }}</td>
                    <td>{{ $sinhvien->khoahoc->name }}</td>
                    <td>{{ $sinhvien->khoachuyenmon->name }}</td>
                    <td>
                        <a href="{{ route('ad.sinhvien.edit', $sinhvien) }}" class="btn btn-sm btn-success">
                            <i class="fa fa-edit"></i>
                        </a>

                        <form class="d-inline-block" action="{{ route('ad.sinhvien.destroy', $sinhvien) }}" method="post" onsubmit="return confirm('Bạn có chắc chắn muốn xóa ?')">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-sm btn-danger" type="submit">
                                <i class="fa fa-trash "></i>
                            </button>
                        </form>
                    </td>
                </tr>
            @endforeach

        </tbody>
    </table>
    {{-- <form action="" method="post" id="formDelete">
        @csrf
        @method('DELETE')
    </form> --}}
    <hr>
    {{ $sinhviens->links() }}
@endsection


{{-- @push('js')
    <script>
        $('.btnDelete').click(function(e) {
            e.preventDefault();
            var _href = $(this).attr('href');
            // alert(href);
            $('#formDelete').attr('action', _href);
            
            if(confirm('Bạn có chắc muốn xóa không ?')) {
                $('#formDelete').submit();
            }
        });
    </script>
@endpush --}}

@stack('name')

@push('name')
    
@endpush