routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Web\HomeController;
use App\Http\Controllers\Web\UserController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\KhoachuyenmonController;
use App\Http\Controllers\Admin\KhoahocController;
use App\Http\Controllers\Admin\SinhvienController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::prefix('admin')->name('ad.')->group(function () {
    Route::get('login', [LoginController::class, 'index'])->name('login.index');
    Route::post('login', [LoginController::class, 'login'])->name('login');

    Route::middleware(['auth'])->group(function () {
        Route::get('/', function () {
            return view('admin.dashboard');
        })->name('dashboard');
    
        Route::resource('category', CategoryController::class)->except('show');
        Route::resource('blog', BlogController::class)->except('show');
        Route::resource('admin', AdminController::class)->except('show');

        Route::resource('sinhvien', SinhvienController::class)->except('show');
        Route::resource('khoahoc', KhoahocController::class)->except('show');
        Route::resource('khoachuyenmon', KhoachuyenmonController::class)->except('show');
    
        Route::get('logout', [LoginController::class, 'logout'])->name('logout');
        Route::get('search', [CategoryController::class, 'search'])->name('category.search');
    });

});


Route::name('w.')->namespace('Web')->group(function(){
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::get('shop', [HomeController::class, 'shop'])->name('shop');

    Route::get('login', [UserController::class, 'login'])->name('login');
    Route::post('login', [UserController::class, 'checklogin'])->name('get.login');

    Route::get('register', [UserController::class, 'register'])->name('register');
    Route::post('register', [UserController::class, 'getregister'])->name('get.register');


});





    

app/Models/Khoahoc.php
<?php

namespace App\Models;

use App\Models\Sinhvien;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Khoahoc extends Model
{
    use HasFactory;
    // protected $table = 'khoahocs';
    protected $fillable = [
        'name'
    ];

    public function sinhviens()
    {
        return $this->hasMany(Sinhvien::class);
    }

     
}

app/Http/Controllers/Admin/KhoahocController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Khoahoc;
use Illuminate\Http\Request;

class KhoahocController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $khoahocs = Khoahoc::all();
        return view('admin.khoahoc.index', compact('khoahocs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.khoahoc.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        Khoahoc::create($data);

        session()->flash('success', 'Thêm thành công');
        return redirect()->route('ad.khoahoc.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Khoahoc $khoahoc)
    {
        return view('admin.khoahoc.edit', compact('khoahoc'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Khoahoc $khoahoc)
    {
        $data = $request->all();
        $khoahoc->update($data);
        return redirect()->route('ad.khoahoc.index')->with('success', 'Đã sửa thành công');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Khoahoc $khoahoc)
    {
        $khoahoc->delete();
        return redirect()->route('ad.khoahoc.index')->with('success', 'Đã xóa thành công');
    }
}

resources/views/admin/khoahoc/create.blade.php
@extends('admin.layouts.master')

@section('content')
    @if ($errors->any())
        <p class="alert alert-danger">
            <span>Vui lòng kiểm tra lại các trường</span>
        </p>
    @endif

    <a class="btn btn-sm btn-success" href="{{ route('ad.khoahoc.index') }}">List Danh mục</a>
    <form method="post" action="{{ route('ad.khoahoc.store') }}" class="text-white">
        @csrf
        <div class="form-row">
            <div class="form-group col-md-12">
                <label for="name">name</label>
                <input type="text" class="form-control" id="name" placeholder="name" name="name" value="{{old('name')}}">
                @error('name')
                    <span class="text-danger">{{ $message }}</span>
                @enderror
            </div>
        </div>


        <button type="submit" class="btn btn-primary">Thêm mới</button>
    </form>
@endsection

resources/views/admin/khoahoc/edit.blade.php
@extends('admin.layouts.master')

@section('content')
    @if ($errors->any())
        <p class="alert alert-danger">
            <span>Vui lòng kiểm tra lại các trường</span>
        </p>
    @endif

    <a class="btn btn-sm btn-success" href="{{ route('ad.khoahoc.index') }}">List Danh mục</a>
    <form method="post" action="{{ route('ad.khoahoc.update', $khoahoc) }}" class="text-white">
        @csrf
        @method('PUT')
        <div class="form-row">
            <div class="form-group col-md-12">
                <label for="name">name</label>
                <input type="text" class="form-control" id="name" placeholder="name" name="name" value="{{$khoahoc->name}}">
                @error('name')
                    <span class="text-danger">{{ $message }}</span>
                @enderror
            </div>
        </div>


        <button type="submit" class="btn btn-primary">Thêm mới</button>
    </form>
@endsection

resources/views/admin/khoahoc/index.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="row mb-3">
        <div class="col-md-6">
            <a class="text-right about-sectiond-inline-block btn btn-success"
                href="{{ route('ad.khoahoc.create') }}">Tạo mới</a>
        </div>
        <div class="col-md-6 text-right">
            <caption>
                <form class="w-100 d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control small" placeholder="Search for..."
                            aria-label="Search" aria-describedby="basic-addon2" name="s">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit">
                                <i class="fa fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </caption>
        </div>
    </div>
    <table class="table table-dark table-hover text-white">
        <thead>
            <tr>
                <th scope="col">Stt</th>
                <th scope="col">Name</th>
                <th scope="col">action</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($khoahocs as $key => $khoahoc)
                <tr>
                    <th scope="row">{{ $key + 1 }}</th>
                    <td>{{ $khoahoc->name }}</td>
                    <td>
                        <a href="{{ route('ad.khoahoc.edit', $khoahoc) }}" class="btn btn-sm btn-success">
                            <i class="fa fa-edit"></i>
                        </a>

                        <form class="d-inline-block" action="{{ route('ad.khoahoc.destroy', $khoahoc) }}" method="post" onsubmit="return confirm('Bạn có chắc chắn muốn xóa ?')">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-sm btn-danger" type="submit">
                                <i class="fa fa-trash "></i>
                            </button>
                        </form>
                    </td>
                </tr>
            @endforeach

        </tbody>
    </table>
    {{-- <form action="" method="post" id="formDelete">
        @csrf
        @method('DELETE')
    </form> --}}
    <hr>
    {{-- {{ $khoahocs->links() }} --}}
@endsection


{{-- @push('js')
    <script>
        $('.btnDelete').click(function(e) {
            e.preventDefault();
            var _href = $(this).attr('href');
            // alert(href);
            $('#formDelete').attr('action', _href);
            
            if(confirm('Bạn có chắc muốn xóa không ?')) {
                $('#formDelete').submit();
            }
        });
    </script>
@endpush --}}

@stack('name')

@push('name')
    
@endpush