routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Web\HomeController;
use App\Http\Controllers\Web\UserController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\LoginController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\KhoachuyenmonController;
use App\Http\Controllers\Admin\KhoahocController;
use App\Http\Controllers\Admin\SinhvienController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::prefix('admin')->name('ad.')->group(function () {
    Route::get('login', [LoginController::class, 'index'])->name('login.index');
    Route::post('login', [LoginController::class, 'login'])->name('login');

    Route::middleware(['auth'])->group(function () {
        Route::get('/', function () {
            return view('admin.dashboard');
        })->name('dashboard');
    
        Route::resource('category', CategoryController::class)->except('show');
        Route::resource('blog', BlogController::class)->except('show');
        Route::resource('admin', AdminController::class)->except('show');

        Route::resource('sinhvien', SinhvienController::class)->except('show');
        Route::resource('khoahoc', KhoahocController::class)->except('show');
        Route::resource('khoachuyenmon', KhoachuyenmonController::class)->except('show');
    
        Route::get('logout', [LoginController::class, 'logout'])->name('logout');
        Route::get('search', [CategoryController::class, 'search'])->name('category.search');
    });

});


Route::name('w.')->namespace('Web')->group(function(){
    Route::get('/', [HomeController::class, 'index'])->name('home');
    Route::get('shop', [HomeController::class, 'shop'])->name('shop');

    Route::get('login', [UserController::class, 'login'])->name('login');
    Route::post('login', [UserController::class, 'checklogin'])->name('get.login');

    Route::get('register', [UserController::class, 'register'])->name('register');
    Route::post('register', [UserController::class, 'getregister'])->name('get.register');


});





    

resources/views/admin/admins/create.blade.php
@extends('admin.layouts.master')

@section('content')
    @if($errors->any())
        <div class="alert alert-danger">
            <span>Email hoặc mật khẩu bị trùng</span>
        </div>
    @endif

    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-settings font-dark"></i>
                        <span class="caption-subject bold uppercase"></span>
                    </div>
                    <div class="actions">
                        <a class="btn btn-circle btn-default" href="{{ route('ad.admin.index') }}" title="">Quay lại</a>
                        <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:void(0);" title="Toàn màn hình"></a>
                    </div>
                </div>
                <div class="portlet-body form">
                    <form action="{{ route('ad.admin.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="name">Tên <span class="required">*</span></label>
                                    <input type="text" id="name" class="form-control" name="name" value="{{ old('name') }}">
                                </div>
                                <div class="form-group">
                                    <label for="email">Email <span class="required">*</span></label>
                                    <input type="email" id="email" class="form-control" name="email" value="{{ old('email') }}">
                                    
                                </div>
                                <div class="form-group">
                                    <label for="phone">Số điện thoại <span class="required">*</span></label>
                                    <input type="text" id="phone" class="form-control" name="phone" value="{{ old('phone') }}">
                                   
                                </div>
                                <div class="form-group">
                                    <label for="password">Mật khẩu <span class="required">*</span></label>
                                    <input type="text" id="password" class="form-control" name="password" value="{{ old('password') }}">
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button class="btn btn-primary">Tạo mới</button>
                            <a href="{{ route('ad.admin.index') }}" class="btn btn-default">Quay lại</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/admins/edit.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-settings font-dark"></i>
                        <span class="caption-subject bold uppercase"></span>
                    </div>
                    <div class="actions">
                        <a class="btn btn-sm btn-success" href="{{ route('ad.admin.index') }}" title="">Quay lại</a>
                        <a class="btn btn-circle btn-icon-only btn-default fullscreen"  title="Toàn màn hình"></a>
                    </div>
                </div>
                <div class="portlet-body form">
                    <form action="{{ route('ad.admin.update', $admin) }}" method="POST" >
                        @method('PUT')
                        @csrf
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label for="name">Tên <span class="required">*</span></label>
                                    <input type="text" id="name" class="form-control" name="name" value="{{ old('name', $admin->name) }}">
                                </div>
                                <div class="form-group">
                                    <label for="email">Email <span class="required">*</span></label>
                                    <input type="text" id="email" class="form-control" disabled value="{{ old('email', $admin->email) }}">
                                </div>
                                <div class="form-group">
                                    <label for="phone">SĐT <span class="required">*</span></label>
                                    <input type="text" id="phone" class="form-control" name="phone" value="{{ old('phone', $admin->phone) }}">
                                </div>
                                <div class="form-group">
                                    <label for="password">Mật khẩu </label>
                                    <input type="text" id="password" class="form-control" name="password"  value="{{ old('password') }}">
                                </div>
                            </div>
                        </div>
                        <div class="form-actions">
                            <button class="btn btn-primary btn-sm">Cập nhật</button>
                            <a href="{{ route('ad.admin.index') }}" class="btn btn-sm btn-success">Quay lại</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/admins/index.blade.php
@extends('admin.layouts.master')

@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light portlet-datatable bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="icon-settings font-dark"></i>
                        <span class="caption-subject bold uppercase">@yield('page_title')</span>
                    </div>
                    <div class="actions">
                        <a href="{{ route('ad.admin.create') }}" class="btn btn-circle btn-sm btn-primary"> <i
                                class="fa fa-plus"></i> Tạo mới</a>
                        <a class="btn btn-circle btn-icon-only btn-default fullscreen" href="javascript:void(0);"
                            title=""></a>
                    </div>
                </div>
                <div class="portlet-body">
                    <table class="table table-striped table-dark" >
                        <thead>
                            <tr>
                                <th>Stt</th>
                                <th>Tên</th>
                                <th>Email</th>
                                <th>SĐT</th>
                                <th width="110">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($admins as $key => $admin)
                                <tr>
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $admin->name }}</td>
                                    <td>{{ $admin->email }}</td>
                                    <td>{{ $admin->phone }}</td>
                                    <td>
                                        <a class="btn btn-circle btn-sm btn-warning"
                                            href="{{ route('ad.admin.edit', $admin) }}"><i class="fa fa-edit"></i></a>
                                        <form action="{{ route('ad.admin.destroy', $admin) }}" id="delete-course-item-form"
                                            style="display: inline-block" method="POST"
                                            onsubmit="return confirm('Bạn có chắc chắn muốn xóa?');">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn btn-circle btn-sm btn-danger"><i
                                                    class="fa fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    {{ $admins->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection